on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest   
    if: github.ref == format('refs/pull/{}/merge', github.event.number)
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  
    - name: Tag
      run: |
        pr_tag="pr${{ github.event.number }}"
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag "${{ pr_tag }}"
        git push origin "${{ pr_tag }}"
    - name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker meta        
      uses: docker/metadata-action@v4
      id: meta
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
